name: CI

on:
  # run deploy when commits to main (as merge)
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npm install

      - name: Run a deploy command
        run: npm run deploy
