name: CI

on:
  # run deploy when commits to main (as merge)
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Git config
        run: |
          git config user.name  ${{ secrets.GIT_NANE }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Install packages
        run: npm install -g yarn && yarn install

      - name: Run a deploy command
        run: yarn run deploy
